version: '3'

services:
  nextjs:
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile
    image: sugar-dating-fe-development

  nginx:
    image: nginx:1.19.0-alpine
    ports:
      - 8000:8000
    environment:
      UPSTREAM_SERVER_URL: nextjs:3000
    volumes:
      - ../../nginx/nginx.conf:/etc/nginx/templates/nginx.conf.template
